# fly.toml app configuration file generated for linebot-subsidy-fastapi on 2023-07-04T13:21:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "${{ secrets.APP_NAME }}"
primary_region = "nrt"

[build]
  image = 'ghcr.io/fionn88/linebot-subsidy-fastapi:latest'

[env]
  DB_HOST = "${{ secrets.DB_HOST }}"
  DB_PASSWORD = "${{ secrets.DB_PASSWORD }}"
  DB_PORT = "${{ secrets.DB_PORT }}"
  DB_SCHEMA = "${{ secrets.DB_SCHEMA }}"
  DB_TABLE = "${{ secrets.DB_TABLE }}"
  DB_USER = "${{ secrets.DB_USER }}"
  LINE_CHANNEL_ACCESS_TOKEN = "${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}"
  LINE_CHANNEL_SECRET = "${{ secrets.LINE_CHANNEL_SECRET }}"
  PORT = "${{ secrets.PORT }}"

[http_service]
  internal_port = ${{ secrets.PORT }}
  force_https = true
  auto_stop_machines = ${{ secrets.AUTO_STOP_MACHINES }}
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
