name: Fly Deploy To Prod
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy fly
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Config file access    
        env:
          APP_HOST: ${{ vars.APP_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_TABLE: ${{ secrets.DB_TABLE }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          PORT: ${{ secrets.PORT }}
          MIN_MACHINES_RUNNING: ${{ vars.MIN_MACHINES_RUNNING }}
          TEAM_EMAIL: ${{ vars.TEAM_EMAIL }}
        run: |
          sed -i -e "s|replace_APP_HOST|\"$APP_HOST\"|g" fly.toml
          sed -i -e "s|replace_DB_PORT|\"$DB_PORT\"|g" fly.toml
          sed -i -e "s|replace_DB_USER|\"$DB_USER\"|g" fly.toml
          sed -i -e "s|replace_DB_PASSWORD|\"$DB_PASSWORD\"|g" fly.toml
          sed -i -e "s|replace_DB_HOST|\"$DB_HOST\"|g" fly.toml
          sed -i -e "s|replace_DB_SCHEMA|\"$DB_SCHEMA\"|g" fly.toml
          sed -i -e "s|replace_DB_TABLE|\"$DB_TABLE\"|g" fly.toml
          sed -i -e "s|replace_LINE_CHANNEL_ACCESS_TOKEN|\"$LINE_CHANNEL_ACCESS_TOKEN\"|g" fly.toml
          sed -i -e "s|replace_LINE_CHANNEL_SECRET|\"$LINE_CHANNEL_SECRET\"|g" fly.toml
          sed -i -e "s|replace_PORT|$PORT|g" fly.toml
          sed -i -e "s|replace_AUTO_STOP_MACHINES|$AUTO_STOP_MACHINES|g" fly.toml
          sed -i -e "s|replace_MIN_MACHINES_RUNNING|$MIN_MACHINES_RUNNING|g" fly.toml
          sed -i -e "s|replace_TEAM_EMAIL|\"$TEAM_EMAIL\"|g" fly.toml
          cat fly.toml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}