# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on: push

jobs:
  deploy:
    name: deploy fly
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Config file access    
        run: |
          sed -i 's/$APP_HOST/${{ vars.APP_HOST }}/g' fly.toml
          sed -i 's/$DB_PORT/${{ secrets.DB_PORT }}/g' fly.toml
          sed -i 's/$DB_USER/${{ secrets.DB_USER }}/g' fly.toml
          sed -i 's/$DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' fly.toml
          sed -i 's/$DB_HOST/${{ secrets.DB_HOST }}/g' fly.toml
          sed -i 's/$DB_SCHEMA/${{ secrets.DB_SCHEMA }}/g' fly.toml
          sed -i 's/$DB_TABLE/${{ secrets.DB_TABLE }}/g' fly.toml
          sed -i 's/$LINE_CHANNEL_ACCESS_TOKEN/${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}/g' fly.toml
          sed -i 's/$LINE_CHANNEL_SECRET/${{ secrets.LINE_CHANNEL_SECRET }}/g' fly.toml
          sed -i 's/$PORT/${{ secrets.PORT }}/g' fly.toml
          sed -i 's/$AUTO_STOP_MACHINES/${{ secrets.AUTO_STOP_MACHINES }}/g' fly.toml
          cat fly.toml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
